# Generated by Django 4.2.11 on 2025-06-27 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm_events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, null=True)),
                ('filters_applied', models.JSONField(blank=True, null=True)),
                ('recipients', models.JSONField()),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL_SUCCESS', 'Partial Success')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('num_recipients', models.IntegerField(default=0)),
                ('num_sent_successfully', models.IntegerField(default=0)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_log',
                'ordering': ['-sent_at'],
            },
        ),
    ]
